"""Configuration load/save for llm-usage.

Config lives at ``./config.toml`` in the current working directory (TOML).
Reads use stdlib ``tomllib``; writes use ``tomli_w``.  API keys may use an
``env:VARNAME`` prefix to reference environment variables instead of storing
plaintext on disk.  Override the path with the ``LLM_USAGE_CONFIG`` env var.
"""

from __future__ import annotations

import os
import tomllib
from pathlib import Path
from typing import Any

import tomli_w

CONFIG_PATH = Path.cwd() / "config.toml"

# The default template generated by ``llm-usage config --init``.
EXAMPLE_CONFIG = """\
# llm-usage configuration
# Credentials: use an "env:VARNAME" prefix to read from environment variables
#              instead of storing plaintext here.
# Volcengine: needs AccessKey/SecretKey (AK/SK) with V4 signing, not Bearer API key.

[platforms.kimi]
enabled = true
api_key = "env:KIMI_API_KEY"            # or "sk-kimi-xxx"
base_url = "https://api.kimi.com/coding/v1"

[platforms.volcengine-coding]
enabled = true
access_key = "env:VOLCENGINE_ACCESS_KEY"   # 火山引擎 AK (AKLT...)
secret_key = "env:VOLCENGINE_SECRET_KEY"   # 火山引擎 SK
plan_type = "coding"                       # coding | agent
tier = "pro"                                # lite | pro
# limits = { "session" = 6000, "weekly" = 45000, "monthly" = 90000 }

[platforms.volcengine-agent]
enabled = true
access_key = "env:VOLCENGINE_ACCESS_KEY"   # 同账户共用 AK/SK
secret_key = "env:VOLCENGINE_SECRET_KEY"
plan_type = "agent"
tier = "medium"                             # small | medium | large | max
# limits = { "5h" = 6000, "weekly" = 45000, "monthly" = 90000 }

[platforms.ollama]
enabled = true
api_key = "env:OLLAMA_API_KEY"           # Ollama Cloud API key

[platforms.opencode-go]
enabled = true
api_key = "env:OPENCODE_GO_API_KEY"       # OpenCode Go API key
"""


def config_path() -> Path:
    """Return the resolved config file path."""
    env = os.environ.get("LLM_USAGE_CONFIG")
    return Path(env) if env else CONFIG_PATH


def config_dir() -> Path:
    return config_path().parent


def load_config(path: Path | None = None) -> dict[str, Any]:
    """Load config from disk; return ``{}`` if missing (never crash)."""
    p = path or config_path()
    if not p.exists():
        return {}
    try:
        with p.open("rb") as fh:
            return tomllib.load(fh)
    except (tomllib.TOMLDecodeError, OSError) as exc:
        raise RuntimeError(f"无法读取配置 {p}: {exc}") from exc


def save_config(config: dict[str, Any], path: Path | None = None) -> Path:
    """Write config to disk as TOML, creating the directory if needed."""
    p = path or config_path()
    p.parent.mkdir(parents=True, exist_ok=True)
    with p.open("wb") as fh:
        tomli_w.dump(config, fh)
    return p


def init_config(path: Path | None = None, overwrite: bool = False) -> Path:
    """Generate the example config template. Raises if it exists and not overwrite."""
    p = path or config_path()
    if p.exists() and not overwrite:
        raise FileExistsError(f"配置已存在：{p}（使用 --force 覆盖）")
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(EXAMPLE_CONFIG, encoding="utf-8")
    return p


def get_platform_config(config: dict[str, Any], platform: str) -> dict[str, Any]:
    """Return a platform section or ``{}`` if absent."""
    return config.get("platforms", {}).get(platform, {}) or {}


def update_platform_config(
    platform: str, updates: dict[str, Any], path: Path | None = None
) -> dict[str, Any]:
    """Merge ``updates`` into [platforms.<platform>], save TOML, return the full updated config."""
    cfg = load_config(path)
    section = cfg.setdefault("platforms", {}).setdefault(platform, {})
    section.update(updates)
    save_config(cfg, path)
    return cfg