"""Configuration load/save for llm-usage.

Config lives at ``./config.toml`` in the current working directory (TOML).
Reads use stdlib ``tomllib``; writes use ``tomli_w``.  API keys may use an
``env:VARNAME`` prefix to reference environment variables instead of storing
plaintext on disk.  Override the path with the ``LLM_USAGE_CONFIG`` env var.
"""

from __future__ import annotations

import os
import tempfile
import threading
import tomllib
from collections.abc import Callable, Iterable
from pathlib import Path
from typing import Any, TypeVar

import tomli_w

CONFIG_PATH = Path.cwd() / "config.toml"

# 进程内互斥:llm-usage web 单 Uvicorn 进程,并发 FastAPI worker 线程共享此锁,
# 保证所有 config.toml 读-改-写在同一临界区内串行(避免丢失更新)。
_CONFIG_LOCK = threading.Lock()

_T = TypeVar("_T")


def _set_sensitive_permissions(path: Path) -> None:
    """Best-effort 0600(凭证明文,收敛文件权限;幂等,失败不阻断)。"""
    try:
        path.chmod(0o600)
    except OSError:
        pass


def _atomic_write_bytes(path: Path, payload: bytes) -> None:
    """原子写:同目录临时文件 + os.replace,读者永远看到完整旧文件或完整新文件。"""
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp_path: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            delete=False,
            dir=path.parent,
            prefix=f".{path.name}.",
            suffix=".tmp",
        ) as fh:
            tmp_path = Path(fh.name)
            fh.write(payload)
            fh.flush()
            os.fsync(fh.fileno())
        _set_sensitive_permissions(tmp_path)
        os.replace(tmp_path, path)
        tmp_path = None
        _set_sensitive_permissions(path)
    finally:
        if tmp_path is not None:
            try:
                tmp_path.unlink()
            except OSError:
                pass


def _write_config_unlocked(config: dict[str, Any], path: Path) -> None:
    """先完整序列化再原子落盘;序列化失败不会触碰目标文件。"""
    _atomic_write_bytes(path, tomli_w.dumps(config).encode("utf-8"))

# The default template generated by ``llm-usage config --init``.
EXAMPLE_CONFIG = """\
# llm-usage configuration
# Credentials: use an "env:VARNAME" prefix to read from environment variables
#              instead of storing plaintext here.
# Volcengine: needs AccessKey/SecretKey (AK/SK) with V4 signing, not Bearer API key.

# 平台显示顺序:可选。取消注释并调整列表即可改变 show/tui/web 的显示顺序。
# platform_order = ["kimi", "volcengine-coding", "volcengine-agent", "ollama", "opencode-go"]

[platforms.kimi]
enabled = true
api_key = "env:KIMI_API_KEY"            # or "sk-kimi-xxx"
base_url = "https://api.kimi.com/coding/v1"
# 多计费套餐:同一平台可有多个独立凭证(每个 = 一个套餐);可在 Web「供应商配置」页维护。
# 手工编辑:
# [[platforms.kimi.credentials]]
# name = "套餐A"
# api_key = "env:KIMI_API_KEY_A"

[platforms.volcengine-coding]
enabled = true
access_key = "env:VOLCENGINE_ACCESS_KEY"   # 火山引擎 AK (AKLT...)
secret_key = "env:VOLCENGINE_SECRET_KEY"   # 火山引擎 SK
plan_type = "coding"                       # coding | agent
tier = "pro"                                # lite | pro
# limits = { "session" = 6000, "weekly" = 45000, "monthly" = 90000 }
# 多计费套餐:同一平台可有多个独立 AK/SK(每个 = 一个套餐);可在 Web「供应商配置」页维护。
# 手工编辑:
# [[platforms.volcengine-coding.credentials]]
# name = "套餐A"
# access_key = "env:VOLCENGINE_ACCESS_KEY_A"
# secret_key = "env:VOLCENGINE_SECRET_KEY_A"

[platforms.volcengine-agent]
enabled = true
access_key = "env:VOLCENGINE_ACCESS_KEY"   # 同账户共用 AK/SK
secret_key = "env:VOLCENGINE_SECRET_KEY"
plan_type = "agent"
tier = "medium"                             # small | medium | large | max
# limits = { "5h" = 6000, "weekly" = 45000, "monthly" = 90000 }
# 多计费套餐:同一平台可有多个独立 AK/SK(每个 = 一个套餐);可在 Web「供应商配置」页维护。
# 手工编辑:
# [[platforms.volcengine-agent.credentials]]
# name = "套餐A"
# access_key = "env:VOLCENGINE_ACCESS_KEY_A"
# secret_key = "env:VOLCENGINE_SECRET_KEY_A"

[platforms.ollama]
enabled = true
api_key = "env:OLLAMA_API_KEY"           # Ollama Cloud API key
# 多计费套餐:同一平台可有多个独立凭证(每个 = 一个套餐);可在 Web「供应商配置」页维护。
# 手工编辑:
# [[platforms.ollama.credentials]]
# name = "套餐A"
# api_key = "env:OLLAMA_API_KEY_A"

[platforms.opencode-go]
enabled = true
api_key = "env:OPENCODE_GO_API_KEY"       # OpenCode Go API key
# 多计费套餐:同一平台可有多个独立凭证(每个 = 一个套餐);可在 Web「供应商配置」页维护。
# 手工编辑:
# [[platforms.opencode-go.credentials]]
# name = "套餐A"
# api_key = "env:OPENCODE_GO_API_KEY_A"

[platforms.clinepass]
enabled = true
api_key = "env:CLINEPASS_API_KEY"         # Cline API key (app.cline.bot)
# 多计费套餐:同一平台可有多个独立凭证(每个 = 一个套餐);可在 Web「供应商配置」页维护。
# 手工编辑:
# [[platforms.clinepass.credentials]]
# name = "套餐A"
# api_key = "env:CLINEPASS_API_KEY_A"

[platforms.llm-gateway]
enabled = true
base_url = "http://127.0.0.1:18080"      # gateway base URL
# API keys 以组为单位配置,每组共享一个每日限额;可在 Web「供应商配置」页维护,
# 或手工编辑。每个 key 可配置显示名称(CLI Key 明细 / Web 悬浮明细展示):
#   api_keys = [{ name = "主Key", value = "env:LLM_GATEWAY_API_KEY" }]
[[platforms.llm-gateway.groups]]
name = "组1"
# daily_limit = 100
api_keys = ["env:LLM_GATEWAY_API_KEY"]
"""


def config_path() -> Path:
    """Return the resolved config file path."""
    env = os.environ.get("LLM_USAGE_CONFIG")
    return Path(env) if env else CONFIG_PATH


def load_config(path: Path | None = None) -> dict[str, Any]:
    """Load config from disk; return ``{}`` if missing (never crash)."""
    p = path or config_path()
    if not p.exists():
        return {}
    try:
        with p.open("rb") as fh:
            return tomllib.load(fh)
    except (tomllib.TOMLDecodeError, OSError) as exc:
        raise RuntimeError(f"无法读取配置 {p}: {exc}") from exc


def save_config(config: dict[str, Any], path: Path | None = None) -> Path:
    """Write config to disk as TOML, creating the directory if needed."""
    p = path or config_path()
    with _CONFIG_LOCK:
        _write_config_unlocked(config, p)
    return p


def init_config(path: Path | None = None, overwrite: bool = False) -> Path:
    """Generate the example config template. Raises if it exists and not overwrite."""
    p = path or config_path()
    with _CONFIG_LOCK:
        if p.exists() and not overwrite:
            raise FileExistsError(f"配置已存在：{p}（使用 --force 覆盖）")
        _atomic_write_bytes(p, EXAMPLE_CONFIG.encode("utf-8"))
    return p


def get_platform_config(config: dict[str, Any], platform: str) -> dict[str, Any]:
    """Return a platform section or ``{}`` if absent."""
    return config.get("platforms", {}).get(platform, {}) or {}


def get_platform_order(config: dict[str, Any]) -> list[str]:
    """Return the configured platform order; unknown keys dropped, unlisted keys appended later by caller."""
    order = config.get("platform_order")
    if not isinstance(order, list):
        return []
    return [k for k in order if isinstance(k, str)]


def mutate_config(
    mutation: Callable[[dict[str, Any]], _T],
    path: Path | None = None,
) -> tuple[dict[str, Any], _T]:
    """串行化读-改-写事务:锁内加载最新配置 → 回调修改 → 原子落盘。

    返回 ``(cfg, mutation_result)``。回调或写盘抛异常时目标文件保持不变。
    回调只能修改传入的字典,不得在锁内调用其它 config 写函数(锁不可重入)。
    """
    p = path or config_path()
    with _CONFIG_LOCK:
        cfg = load_config(p)
        result = mutation(cfg)
        _write_config_unlocked(cfg, p)
    return cfg, result


def set_platform_order(order: list[str], path: Path | None = None) -> dict[str, Any]:
    """Persist platform_order to TOML; return the full updated config."""
    cfg, _ = mutate_config(lambda c: c.__setitem__("platform_order", order), path)
    return cfg


def update_platform_config(
    platform: str,
    updates: dict[str, Any],
    path: Path | None = None,
    *,
    remove_fields: Iterable[str] = (),
) -> dict[str, Any]:
    """Merge ``updates`` into [platforms.<platform>], then pop ``remove_fields``.

    Single atomic save; returns the full updated config.
    """
    def _apply(cfg: dict[str, Any]) -> None:
        section = cfg.setdefault("platforms", {}).setdefault(platform, {})
        section.update(updates)
        for field in remove_fields:
            section.pop(field, None)

    cfg, _ = mutate_config(_apply, path)
    return cfg


def remove_platform_config(
    platform: str, path: Path | None = None
) -> dict[str, Any]:
    """Remove [platforms.<platform>] entirely, save TOML, return the full updated config."""
    def _remove(cfg: dict[str, Any]) -> None:
        cfg.get("platforms", {}).pop(platform, None)

    cfg, _ = mutate_config(_remove, path)
    return cfg

