"""Configuration load/save for llm-usage.

Config lives at ``./config.toml`` in the current working directory (TOML).
Reads use stdlib ``tomllib``; writes use ``tomli_w``.  API keys may use an
``env:VARNAME`` prefix to reference environment variables instead of storing
plaintext on disk.  Override the path with the ``LLM_USAGE_CONFIG`` env var.
"""

from __future__ import annotations

import os
import tomllib
from pathlib import Path
from typing import Any

import tomli_w

CONFIG_PATH = Path.cwd() / "config.toml"

# The default template generated by ``llm-usage config --init``.
EXAMPLE_CONFIG = """\
# llm-usage configuration
# Credentials: use an "env:VARNAME" prefix to read from environment variables
#              instead of storing plaintext here.
# Volcengine: needs AccessKey/SecretKey (AK/SK) with V4 signing, not Bearer API key.

# 平台显示顺序:可选。取消注释并调整列表即可改变 show/tui/web 的显示顺序。
# platform_order = ["kimi", "volcengine-coding", "volcengine-agent", "ollama", "opencode-go"]

[platforms.kimi]
enabled = true
api_key = "env:KIMI_API_KEY"            # or "sk-kimi-xxx"
base_url = "https://api.kimi.com/coding/v1"
# 多计费套餐:同一平台可有多个独立凭证(每个 = 一个套餐);可在 Web「供应商配置」页维护。
# 手工编辑:
# [[platforms.kimi.credentials]]
# name = "套餐A"
# api_key = "env:KIMI_API_KEY_A"

[platforms.volcengine-coding]
enabled = true
access_key = "env:VOLCENGINE_ACCESS_KEY"   # 火山引擎 AK (AKLT...)
secret_key = "env:VOLCENGINE_SECRET_KEY"   # 火山引擎 SK
plan_type = "coding"                       # coding | agent
tier = "pro"                                # lite | pro
# limits = { "session" = 6000, "weekly" = 45000, "monthly" = 90000 }
# 多计费套餐:同一平台可有多个独立 AK/SK(每个 = 一个套餐);可在 Web「供应商配置」页维护。
# 手工编辑:
# [[platforms.volcengine-coding.credentials]]
# name = "套餐A"
# access_key = "env:VOLCENGINE_ACCESS_KEY_A"
# secret_key = "env:VOLCENGINE_SECRET_KEY_A"

[platforms.volcengine-agent]
enabled = true
access_key = "env:VOLCENGINE_ACCESS_KEY"   # 同账户共用 AK/SK
secret_key = "env:VOLCENGINE_SECRET_KEY"
plan_type = "agent"
tier = "medium"                             # small | medium | large | max
# limits = { "5h" = 6000, "weekly" = 45000, "monthly" = 90000 }
# 多计费套餐:同一平台可有多个独立 AK/SK(每个 = 一个套餐);可在 Web「供应商配置」页维护。
# 手工编辑:
# [[platforms.volcengine-agent.credentials]]
# name = "套餐A"
# access_key = "env:VOLCENGINE_ACCESS_KEY_A"
# secret_key = "env:VOLCENGINE_SECRET_KEY_A"

[platforms.ollama]
enabled = true
api_key = "env:OLLAMA_API_KEY"           # Ollama Cloud API key
# 多计费套餐:同一平台可有多个独立凭证(每个 = 一个套餐);可在 Web「供应商配置」页维护。
# 手工编辑:
# [[platforms.ollama.credentials]]
# name = "套餐A"
# api_key = "env:OLLAMA_API_KEY_A"

[platforms.opencode-go]
enabled = true
api_key = "env:OPENCODE_GO_API_KEY"       # OpenCode Go API key
# 多计费套餐:同一平台可有多个独立凭证(每个 = 一个套餐);可在 Web「供应商配置」页维护。
# 手工编辑:
# [[platforms.opencode-go.credentials]]
# name = "套餐A"
# api_key = "env:OPENCODE_GO_API_KEY_A"

[platforms.llm-gateway]
enabled = true
base_url = "http://127.0.0.1:18080"      # gateway base URL
# API keys 以组为单位配置,每组共享一个每日限额;可在 Web「供应商配置」页维护,
# 或手工编辑。每个 key 可配置显示名称(CLI Key 明细 / Web 悬浮明细展示):
#   api_keys = [{ name = "主Key", value = "env:LLM_GATEWAY_API_KEY" }]
[[platforms.llm-gateway.groups]]
name = "组1"
# daily_limit = 100
api_keys = ["env:LLM_GATEWAY_API_KEY"]
"""


def config_path() -> Path:
    """Return the resolved config file path."""
    env = os.environ.get("LLM_USAGE_CONFIG")
    return Path(env) if env else CONFIG_PATH


def load_config(path: Path | None = None) -> dict[str, Any]:
    """Load config from disk; return ``{}`` if missing (never crash)."""
    p = path or config_path()
    if not p.exists():
        return {}
    try:
        with p.open("rb") as fh:
            return tomllib.load(fh)
    except (tomllib.TOMLDecodeError, OSError) as exc:
        raise RuntimeError(f"无法读取配置 {p}: {exc}") from exc


def save_config(config: dict[str, Any], path: Path | None = None) -> Path:
    """Write config to disk as TOML, creating the directory if needed."""
    p = path or config_path()
    p.parent.mkdir(parents=True, exist_ok=True)
    with p.open("wb") as fh:
        tomli_w.dump(config, fh)
    try:
        p.chmod(0o600)  # 凭证明文,收敛文件权限(幂等)
    except OSError:
        pass
    return p


def init_config(path: Path | None = None, overwrite: bool = False) -> Path:
    """Generate the example config template. Raises if it exists and not overwrite."""
    p = path or config_path()
    if p.exists() and not overwrite:
        raise FileExistsError(f"配置已存在：{p}（使用 --force 覆盖）")
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(EXAMPLE_CONFIG, encoding="utf-8")
    try:
        p.chmod(0o600)  # 与 save_config 一致(幂等)
    except OSError:
        pass
    return p


def get_platform_config(config: dict[str, Any], platform: str) -> dict[str, Any]:
    """Return a platform section or ``{}`` if absent."""
    return config.get("platforms", {}).get(platform, {}) or {}


def get_platform_order(config: dict[str, Any]) -> list[str]:
    """Return the configured platform order; unknown keys dropped, unlisted keys appended later by caller."""
    order = config.get("platform_order")
    if not isinstance(order, list):
        return []
    return [k for k in order if isinstance(k, str)]


def set_platform_order(order: list[str], path: Path | None = None) -> dict[str, Any]:
    """Persist platform_order to TOML; return the full updated config."""
    cfg = load_config(path)
    cfg["platform_order"] = order
    save_config(cfg, path)
    return cfg


def update_platform_config(
    platform: str, updates: dict[str, Any], path: Path | None = None
) -> dict[str, Any]:
    """Merge ``updates`` into [platforms.<platform>], save TOML, return the full updated config."""
    cfg = load_config(path)
    section = cfg.setdefault("platforms", {}).setdefault(platform, {})
    section.update(updates)
    save_config(cfg, path)
    return cfg